server:
  port: 8080

spring:
  application:
    name: my-spring-app

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

security:
  oauth2:
    client:
      registration:
        ping:
          client-id: spring-app
          client-secret: hgPFFcaqm8GN4eNA1nrffoSoA798N1jLQpkAx20NqFj0cEiKwQ74v1mAiBCIDbyC
          scope: openid, profile
          redirect-uri: "http://localhost:8080/login/oauth2/code/pingfederate"
      provider:
        ping:
          authorization-uri: https://localhost:9031/as/authorization.oauth2
          token-uri: https://localhost:9031/as/token.oauth2
          user-info-uri: https://localhost:9031/idp/userinfo.openid
