spring:
  application:
    name: spring-pingfed-pingdir

  security:
    oauth2:
      client:
        registration:
          pingfederate:
            client-id: your-client-id
            client-secret: your-client-secret
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          pingfederate:
            issuer-uri: https://localhost:9031
            authorization-uri: https://localhost:9031/as/authorization.oauth2
            token-uri: https://localhost:9031/as/token.oauth2
            user-info-uri: https://localhost:9031/idp/userinfo.openid
            jwk-set-uri: https://localhost:9031/pf/JWKS
            user-name-attribute: sub

  ldap:
    urls: ldaps://localhost:1636
    base: dc=example,dc=com
    username: cn=administrator
    password: 2FederateM0re